[package]
name = "workflow-wasm-macros"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description = "Macros for workflow-wasm"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn.workspace = true
quote = "1.0.21"
proc-macro2="1.0.43"
proc-macro-error3 = { version = "3", default-features = false }
js-sys.workspace = true
wasm-bindgen.workspace = true
