[package]
name = "workflow-serializer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
include.workspace = true
repository.workspace = true

[dependencies]
borsh.workspace = true
serde.workspace = true
ahash.workspace = true
